### ISSUE TITLE
Enable alloc feature for base64 dependency

### ISSUE THREAD

**Issue by dvzrv** [Nitrokey/nethsm-sdk-rs#14]
Hi! :wave: 

I'm using this crate in the context of [nethsm](https://crates.io/crates/nethsm).
I noticed that I am no longer able to upgrade my lock file as this leads to clippy failing:

```
    Checking nethsm-sdk-rs v1.0.0
error[E0599]: no method named `encode` found for struct `GeneralPurpose` in the current scope
   --> /home/dave/.local/state/cargo/registry/src/index.crates.io-6f17d22bba15001f/nethsm-sdk-rs-1.0.0/src/apis/mod.rs:122:51
    |
122 |     format!("Basic {}", general_purpose::STANDARD.encode(string)).to_string()
    |                                                   ^^^^^^ method not found in `GeneralPurpose`

```

This appears to be broken if base64 >=0.22.0 is pulled in by another dependency in the tree.

Do you have a timeline for updating/ adapting this crate (its last release is from six months ago)?

**Comment by robin-nitrokey** [comment]
The cause for this problem is that we do not enable the `alloc` feature for `base64` in our `Cargo.toml`.  Probably some dependency does, but when it updates `base64` to an incompatible version, the feature is no longer enabled for our version.

You should be able to temporarily fix this on your side by manually pulling in `base64` and activating the feature:

```
[dependencies]
base64 = { version = "0.21", default-features = false, features = ["alloc"] }
```
