### ISSUE TITLE
Is the backup format stable?

### ISSUE THREAD

**Issue by wiktor-k** [Nitrokey/nethsm-sdk-rs#36]
Hi folks,

We're writing a tool to inspect the consistency of backups and have been wondering to what extend can we describe / rely on backup format and the keys in it to stay consistent: https://gitlab.archlinux.org/archlinux/signstar/-/merge_requests/99#note_226496

Is the backup format considered an internal detail or can we be sure it will mostly stay the same? What about the keys within the decrypted backup file?

Thank you for your time! :wave:

**Comment by robin-nitrokey** [comment]
That’s a question for @ansiwen.

My understanding is that the (outer) backup format is versioned and breaking changes would trigger a version bump.  The (inner) data keys are unlikely to change but are not guaranteed to stay the same.  It is only guaranteed that the backup can be applied, i. e. the NetHSM would transform the keys to the new scheme if there was a change to the internal data layout.

**Comment by wiktor-k** [comment]
AFAICS the inner format is also versioned (both of these are zeros currently). I forgot to ask if this a correct repo to discuss anyway but it seems it's not the worst place :sweat_smile: 

Thanks for help! I'll wait to see what @ansiwen will add :)

**Comment by jans23** [comment]
I didn't check the details but I assume the inner format is the one consistent to the database structure. In this case, it will change sooner or later if a software update results in a new DB structure, e.g. if new columns are added.

The outer format is expected to change less often but will be changed eventually if we add new features affecting the backup format such as m-of-n scheme (which will likely replace the backup passphrase).

**Comment by ansiwen** [comment]
> Is the backup format considered an internal detail or can we be sure it will mostly stay the same?

In general yes, it is an internal detail. However, we will always stay backwards compatible, so old backups will always be able to be imported.

So, actually, there is only one backup format, which is a binary encrytped key-value format. This will be stable as long as the version number doesn't change. We have a python tool, to dump the content as a JSON object: https://github.com/Nitrokey/nethsm/blob/main/src/keyfender/bin/export_backup.py

The structure of the keys and values is just a 1:1 dump of our KV database. The KV-keys look like file paths, and it's unlikely this will ever change, but of course there will be new "files" and "directories" over time. The KV-value data is an encrypted json structure, and this is even more internal. Usually we add new data as optional fields, in order to avoid an explicit migration step, and migrate the data on the fly.

**Comment by wiktor-k** [comment]
Great input folks, thank you!

Just for the record we've already implemented a parser and decryptor in Rust: https://gitlab.archlinux.org/archlinux/signstar/-/merge_requests/99/diffs#diff-content-f73fd25c4f6373648cce168bdd7f48f35f6839e5 but we were wondering to what degree should we expose the internals.

I'm closing this issue since the question has been answered to my satisfaction.

Have a nice evening! 👋
